
select
    SIRASGN.SIRASGN_PIDM,
    RII.LFMI_NAME,
    f_get_desc_fnc('STVDEPT', SCBCRSE_DEPT_CODE, 30) as Intsr_Dept,
    SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID ,
    SSBSECT.SSBSECT_SUBJ_CODE ,
    SSBSECT.SSBSECT_CRSE_NUMB ,
    SSBSECT.SSBSECT_SEQ_NUMB,
    SCBCRSE.SCBCRSE_TITLE ,    
    SGBSTDN.SGBSTDN_LEVL_CODE ,   
    (COUNT(SGBSTDN.SGBSTDN_LEVL_CODE)) as Count,
    SFRSTCR.SFRSTCR_CREDIT_HR Cred_Hr,
    (COUNT(SGBSTDN.SGBSTDN_LEVL_CODE)) * (SFRSTCR.SFRSTCR_CREDIT_HR) Total_Cred_Hr
    
    from SFRSTCR SFRSTCR

    inner join SSBSECT SSBSECT on SSBSECT.SSBSECT_CRN = SFRSTCR_CRN and SSBSECT_TERM_CODE = SFRSTCR_TERM_CODE

    left outer join STVCLAS STVCLAS on STVCLAS.STVCLAS_CODE = f_class_calc_fnc(SFRSTCR.SFRSTCR_PIDM,SFRSTCR.SFRSTCR_LEVL_CODE, SFRSTCR_TERM_CODE)

    left outer join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SFRSTCR_PIDM
         and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, SFRSTCR.SFRSTCR_TERM_CODE)
         AND SGBSTDN.SGBSTDN_LEVL_CODE IN ('UG', 'GR')

    JOIN SCBCRSE SCBCRSE on SCBCRSE.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE
         AND SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
         AND SCBCRSE.SCBCRSE_EFF_TERM = (SELECT MAX(SCBCRSE.SCBCRSE_EFF_TERM)
                                        FROM SCBCRSE SCBCRSEX
                                        WHERE SCBCRSEX.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE
                                        AND SCBCRSEX.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
                                        AND SCBCRSEX.SCBCRSE_EFF_TERM <= SSBSECT.SSBSECT_TERM_CODE
                                  )

    left outer join SIRASGN SIRASGN on SIRASGN.SIRASGN_PIDM IS NOT NULL
         and SIRASGN.SIRASGN_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
         and SIRASGN.SIRASGN_CRN = SFRSTCR.SFRSTCR_CRN

    left outer join rel_identity_instructor rii on rii.pidm = sirasgn.sirasgn_pidm

where
    'Y' = f_registered_this_term(SFRSTCR.SFRSTCR_PIDM, SFRSTCR.SFRSTCR_TERM_CODE)
    and SFRSTCR.SFRSTCR_TERM_CODE = 202140 --:parm_term_code_select.STVTERM_CODE
    and SSBSECT_TOT_CREDIT_HRS > 0
    and SFRSTCR.SFRSTCR_CREDIT_HR > 0
    and SFRSTCR.SFRSTCR_GMOD_CODE not in ('Y')

      
GROUP BY
    SGBSTDN.SGBSTDN_LEVL_CODE,
    SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID,
    SSBSECT.SSBSECT_SUBJ_CODE,
    SSBSECT.SSBSECT_CRSE_NUMB,
    SSBSECT.SSBSECT_SEQ_NUMB,
    SCBCRSE.SCBCRSE_TITLE,
    SIRASGN.SIRASGN_PIDM,
    RII.LFMI_NAME,
    f_get_desc_fnc('STVDEPT', SCBCRSE_DEPT_CODE, 30),
    SFRSTCR.SFRSTCR_CREDIT_HR

order by
      LFMI_NAME, SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID, SGBSTDN.SGBSTDN_LEVL_CODE
